/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const Report = IDL.Record({
  'id' : IDL.Nat,
  'status' : IDL.Text,
  'content' : IDL.Text,
  'clientName' : IDL.Text,
  'createdAt' : IDL.Int,
  'reportDate' : IDL.Text,
  'reportType' : IDL.Text,
  'reportNumber' : IDL.Text,
});

export const idlService = IDL.Service({
  'createReport' : IDL.Func([IDL.Text, IDL.Text], [IDL.Nat], []),
  'deleteReport' : IDL.Func([IDL.Nat], [IDL.Bool], []),
  'getReport' : IDL.Func([IDL.Nat], [IDL.Opt(Report)], ['query']),
  'listReports' : IDL.Func([], [IDL.Vec(Report)], ['query']),
  'updateReport' : IDL.Func(
      [IDL.Nat, IDL.Text, IDL.Text, IDL.Text, IDL.Text],
      [IDL.Bool],
      [],
    ),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const Report = IDL.Record({
    'id' : IDL.Nat,
    'status' : IDL.Text,
    'content' : IDL.Text,
    'clientName' : IDL.Text,
    'createdAt' : IDL.Int,
    'reportDate' : IDL.Text,
    'reportType' : IDL.Text,
    'reportNumber' : IDL.Text,
  });
  
  return IDL.Service({
    'createReport' : IDL.Func([IDL.Text, IDL.Text], [IDL.Nat], []),
    'deleteReport' : IDL.Func([IDL.Nat], [IDL.Bool], []),
    'getReport' : IDL.Func([IDL.Nat], [IDL.Opt(Report)], ['query']),
    'listReports' : IDL.Func([], [IDL.Vec(Report)], ['query']),
    'updateReport' : IDL.Func(
        [IDL.Nat, IDL.Text, IDL.Text, IDL.Text, IDL.Text],
        [IDL.Bool],
        [],
      ),
  });
};

export const init = ({ IDL }) => { return []; };