import type { VehicleReport } from "./types";

export function createDefaultReport(id: string): VehicleReport {
  return {
    id,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
    status: "draft",
    valuationNo: "",
    agencyName: "",
    valuatorName: "Dinesh Kumar Jangir",
    inspectionDateTime: "",
    placeOfInspection: "",
    ownerAddress: "",
    hypo: "",
    ownershipTransfer: "",
    registrationNumber: "",
    dateOfRegistrationPurchase: "",
    chassisNumber: "",
    engineNumber: "",
    odometerHourMeter: "",
    makeModel: "",
    colour: "",
    manufacturingYear: "",
    classOfVehicle: "",
    typeOfBody: "",
    roadTaxPaidUpto: "",
    registrationVerifiedPhysically: "Yes",
    modelOfAsset: "",
    noOfCylinders: "",
    horsePower: "",
    cubicCapacity: "",
    fuelUsed: "",
    transmission: "",
    appearance: "Normal",
    ignition: "Smooth Working",
    gearShifting: "Normal",
    battery: "Normal",
    lights: "Working",
    chassisFrame: "Normal",
    engine: "Normal",
    body: "Good",
    tyres: "Good",
    upholstery: "Good",
    musicSystem: "Mounted",
    spareWheel: "Ok",
    tools: "Ok",
    insurerName: "",
    idvValidity: "",
    policyNo: "",
    accidentHistory: "Not Known",
    majorRepair: "Not Known",
    useMaintenance: "Good",
    valuationAmount: "",
  };
}
